[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
update_changelog_on_bump = true
major_version_zero = true
version = "0.6.0"
version_files = [
  "canfund-rs/Cargo.toml:version",
]
